spring:
  application:
    name: message-service
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-O:
          destination: send-communication
          group: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

server:
  port: 9010